// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvxHiLMhslznrMhhTAMq6tQYnh2AosoiM',
    appId: '1:971939937891:web:9049b58ca8168c174d4256',
    messagingSenderId: '971939937891',
    projectId: 'perpustakaan-4529c',
    authDomain: 'perpustakaan-4529c.firebaseapp.com',
    storageBucket: 'perpustakaan-4529c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKItmOkxJurDMkj7pvGc3rgkYWxc0Canw',
    appId: '1:971939937891:android:c5d8bc086d77b92f4d4256',
    messagingSenderId: '971939937891',
    projectId: 'perpustakaan-4529c',
    storageBucket: 'perpustakaan-4529c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAfbO1LHXoH4mN613kUYkuj0fVoFiPB4w',
    appId: '1:971939937891:ios:61caeab9c2d5ab484d4256',
    messagingSenderId: '971939937891',
    projectId: 'perpustakaan-4529c',
    storageBucket: 'perpustakaan-4529c.appspot.com',
    iosClientId: '971939937891-3nbie3r68jkau9hkri92johks1vo23bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.perpus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAfbO1LHXoH4mN613kUYkuj0fVoFiPB4w',
    appId: '1:971939937891:ios:61caeab9c2d5ab484d4256',
    messagingSenderId: '971939937891',
    projectId: 'perpustakaan-4529c',
    storageBucket: 'perpustakaan-4529c.appspot.com',
    iosClientId: '971939937891-3nbie3r68jkau9hkri92johks1vo23bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.perpus',
  );
}
